### ISSUE TITLE
Develop a to-do endpoint

### ISSUE THREAD

**Issue by arellaTV** [wizardchess/social-video-board#12]
AC:

- [ ] Create a 'to-do' database
- [ ] Create a 'task' table
- [ ] `GET` returns an array from the '/todo' endpoint
- [ ] `POST` adds a todo record to the 'task' table
